update tag

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -5,8 +5,9 @@ extend = [
   { path = "src/risedevtool/etcd.toml" },
   { path = "src/risedevtool/jaeger.toml" },
   { path = "src/risedevtool/kafka.toml" },
+  { path = "src/risedevtool/redis.toml" },
   { path = "src/risedevtool/risedev-components.toml" },
-  { path = "src/frontend/test_runner/planner_test.toml" },
+  { path = "src/frontend/planner_test/planner_test.toml" },
 ]
 
 env_files = ["./risedev-components.user.env"]
@@ -21,11 +22,10 @@ is_all_in_one_enabled = get_env ENABLE_ALL_IN_ONE
 if ${is_sanitizer_enabled}
   set_env RISEDEV_CARGO_BUILD_EXTRA_ARGS "-Zbuild-std --target ${CARGO_MAKE_RUST_TARGET_TRIPLE}"
   set_env RISEDEV_BUILD_TARGET_DIR "${CARGO_MAKE_RUST_TARGET_TRIPLE}/"
-  set_env RISEDEV_RUSTFLAGS "--cfg tokio_unstable -Zsanitizer=thread"
+  set_env RISEDEV_RUSTFLAGS "-Ctarget-cpu=native --cfg tokio_unstable -Zsanitizer=thread"
 else
   set_env RISEDEV_CARGO_BUILD_EXTRA_ARGS ""
   set_env RISEDEV_BUILD_TARGET_DIR ""
-  set_env RISEDEV_RUSTFLAGS "--cfg tokio_unstable"
 end
 
 if ${is_all_in_one_enabled}
@@ -59,6 +59,7 @@ script = '''
 rm -rf "${PREFIX_DATA}"
 rm -rf "${PREFIX_LOG}"
 rm -rf "${PREFIX_CONFIG}"
+rm -rf "${PREFIX_PROFILING}"
 '''
 
 
@@ -111,12 +112,23 @@ if (( "$(du -sk ${PREFIX_LOG} | cut -f1)" > 2000 )) ; then
 fi
 '''
 
+[tasks.doc]
+category = "Misc"
+description = "Open rustdoc for piestream"
+dependencies = ["build-docs"]
+script = '''
+#!/bin/bash
+set -e
+
+python -mwebbrowser file://$(pwd)/target/doc/index.html
+'''
+
 [tasks.link-standalone-binaries]
 category = "RiseDev - Build"
 description = "Link standalone cmds to RiseDev bin"
 condition = { env_not_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -f "${PREFIX_BIN}/compute-node"
 rm -f "${PREFIX_BIN}/meta-node"
@@ -133,7 +145,7 @@ category = "RiseDev - Build"
 description = "Link all-in-one cmds to RiseDev bin"
 condition = { env_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_BIN}/piestream"
@@ -151,7 +163,7 @@ category = "RiseDev - Build"
 description = "Link all binaries to .bin"
 condition = { env_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_USR_BIN}"
@@ -184,7 +196,7 @@ category = "RiseDev - Build"
 description = "Extract dashboard artifact"
 condition = { env_not_set = ["ENABLE_BUILD_DASHBOARD_V2"] }
 script = '''
-#!@shell
+#!/bin/bash
 
 # we allow this script to fail
 
@@ -200,7 +212,7 @@ category = "RiseDev - Build"
 description = "Build dashboard v2"
 condition = { env_set = ["ENABLE_BUILD_DASHBOARD_V2"] }
 script = """
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_UI}"
@@ -213,13 +225,13 @@ category = "RiseDev - Build"
 description = "Build Rust components"
 condition = { env_set = ["ENABLE_BUILD_RUST"] }
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 echo "$(tput setaf 4)$(tput bold)[Reminder]$(tput sgr0) risedev will only build $(tput setaf 4)piestream_cmd(_all) and risedev$(tput sgr0) crates."
 
-export RUSTFLAGS="${RISEDEV_RUSTFLAGS}"
-echo + RUSTFLAGS="$RUSTFLAGS"
+[[ -z "${RISEDEV_RUSTFLAGS}" ]] || export RUSTFLAGS="${RISEDEV_RUSTFLAGS}"
+echo + RUSTFLAGS="${RUSTFLAGS:-<not set>}"
 set -xe
 cargo build -p ${RISEDEV_CARGO_BUILD_CRATE} -p risedev \
             --profile "${piestream_BUILD_PROFILE}" \
@@ -231,7 +243,7 @@ category = "RiseDev - Build"
 description = "Clean Rust targets"
 condition = { env_set = ["ENABLE_BUILD_RUST"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 cargo clean
 '''
@@ -240,8 +252,9 @@ cargo clean
 category = "RiseDev - Build"
 description = "Build Rust docs"
 condition = { env_set = ["ENABLE_BUILD_RUST"] }
+env = { RUSTDOCFLAGS = "--markdown-css ../../docs/rust.css --markdown-no-toc --index-page docs/index.md -Zunstable-options" }
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -252,7 +265,7 @@ cargo doc --workspace --no-deps --document-private-items
 category = "RiseDev - Prepare"
 description = "Copy necessary configuration files to RiseDev"
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -261,9 +274,9 @@ cp "src/risedevtool/run_command.sh" "${PREFIX_BIN}/run_command.sh"
 cp "src/risedevtool/welcome.sh" "${PREFIX_BIN}/welcome.sh"
 '''
 
-[tasks.pre-start-playground]
+[tasks.pre-start-dev]
 category = "RiseDev - Prepare"
-description = "Prepare playground by downloading necessary tools and build required components"
+description = "Prepare dev cluster by downloading necessary tools and build required components"
 dependencies = [
   "download-minio",
   "download-mcli",
@@ -272,11 +285,26 @@ dependencies = [
   "download-prometheus",
   "download-jaeger",
   "download-kafka",
+  "download-redis",
   "build-piestream",
   "post-build-piestream",
   "extract-dashboard-artifact",
   "export-dashboard-v2",
   "prepare-config",
+]
+
+[tasks.pre-start-benchmark]
+category = "RiseDev - Prepare"
+description = "Download necessary tools to deploy a benchmark env"
+dependencies = [
+  "download-minio",
+  "download-mcli",
+  "download-etcd",
+  "download-grafana",
+  "download-prometheus",
+  "download-jaeger",
+  "download-kafka",
+  "download-redis",
 ]
 
 [tasks.p]
@@ -286,7 +314,7 @@ alias = "playground"
 category = "RiseDev - Start"
 description = "Start a lite piestream playground using piestream all-in-one binary"
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -301,7 +329,7 @@ RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin piestream --profile "${piest
 category = "RiseDev - Start"
 description = "Start RiseCtl"
 script = '''
-#!@shell
+#!/bin/bash
 
 RC_ENV_FILE="${PREFIX_CONFIG}/risectl-env"
 
@@ -321,10 +349,10 @@ alias = "dev"
 
 [tasks.dev]
 category = "RiseDev - Start"
-dependencies = ["pre-start-playground"]
-command = "target/${BUILD_MODE_DIR}/risedev-playground"
+dependencies = ["pre-start-dev"]
+command = "target/${BUILD_MODE_DIR}/risedev-dev"
 args = ["${@}"]
-description = "Start a full piestream dev cluster using risedev-playground"
+description = "Start a full piestream dev cluster using risedev-dev"
 
 [tasks.kafka]
 category = "RiseDev - Start"
@@ -354,17 +382,14 @@ category = "RiseDev - Stop"
 description = "Kill piestream dev cluster and clean the data"
 dependencies = ["k", "clean-data"]
 
-[tasks.fill-kafka]
-command = "scripts/source/prepare_source.sh"
-
 [tasks.install-tools]
 category = "RiseDev - Check"
 script = """
-#!@shell
+#!/bin/bash
 
 set -e
 
-for tool in cargo-llvm-cov cargo-nextest cargo-udeps cargo-hakari cargo-sort cargo-make
+for tool in cargo-llvm-cov cargo-nextest cargo-udeps cargo-hakari cargo-sort cargo-make typos-cli
 do
   echo "install: $(tput setaf 4)$tool$(tput sgr0)"
   cargo install $tool --locked
@@ -372,15 +397,11 @@ do
 done
 
 echo "install: $(tput setaf 4)risinglightdb/sqllogictest-rs$(tput sgr0)"
-cargo install --git https://github.com/risinglightdb/sqllogictest-rs --features bin
+cargo install --git https://github.com/risinglightdb/sqllogictest-rs --bin sqllogictest
 echo
 
 echo "check: $(tput setaf 4)tmux >= v3.2a$(tput sgr0)"
 tmux -V || echo "$(tput setaf 3)tmux$(tput sgr0) not found."
-echo
-
-echo "check: $(tput setaf 4)yq >= 4$(tput sgr0)"
-yq -V || echo "$(tput setaf 3)yq$(tput sgr0) not found."
 echo
 
 echo "check: $(tput setaf 4)psql >= 14$(tput sgr0)"
@@ -389,6 +410,10 @@ echo
 
 echo "check: $(tput setaf 4)cmake$(tput sgr0)"
 cmake --version || echo "$(tput setaf 3)cmake$(tput sgr0) not found."
+echo
+
+echo "check: $(tput setaf 4)protoc$(tput sgr0)"
+protoc --version || echo "$(tput setaf 3)protoc$(tput sgr0) not found."
 echo
 """
 description = "Install required tools to do pre-CI check and run e2e tests"
@@ -426,31 +451,108 @@ description = "Run unit tests"
 category = "RiseDev - Build in simulation mode"
 description = "Build in simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
 
-cargo build "$@"
+cargo build \
+  -p piestream_batch \
+  -p piestream_common \
+  -p piestream_compute \
+  -p piestream_connector \
+  -p piestream_frontend \
+  -p piestream_meta \
+  -p piestream_object_store \
+  -p piestream_source \
+  -p piestream_storage \
+  -p piestream_stream \
+  -p pgwire \
+  "$@"
 """
 
 [tasks.stest]
 category = "RiseDev - Deterministic Simulation Test"
 description = "Run unit tests in deterministic simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
 
-cargo nextest run "$@"
+cargo nextest run \
+  -p piestream_batch \
+  -p piestream_common \
+  -p piestream_compute \
+  -p piestream_connector \
+  -p piestream_frontend \
+  -p piestream_meta \
+  -p piestream_object_store \
+  -p piestream_source \
+  -p piestream_storage \
+  -p piestream_stream \
+  -p pgwire \
+  "$@"
+"""
+
+[tasks.sscale-test]
+category = "RiseDev - Simulation scaling tests"
+description = "Run integration scaling tests in deterministic simulation mode"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+script = """
+#!/bin/bash
+set -e
+
+cargo nextest run \
+  -p piestream_simulation_scale \
+  "$@"
+"""
+
+[tasks.sarchive-scale-test]
+category = "RiseDev - Simulation scaling tests"
+description = "Archive integration scaling tests in deterministic simulation mode"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+script = """
+#!/bin/bash
+set -e
+
+cargo nextest archive \
+  -p piestream_simulation_scale \
+  --archive-file scale-test.tar.zst \
+  "$@"
+"""
+
+[tasks.sslt]
+category = "RiseDev - Deterministic Simulation End-to-end Test"
+description = "Run e2e tests in deterministic simulation mode"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+script = """
+#!/bin/bash
+set -e
+
+cargo run -p piestream_simulation "$@"
+"""
+
+[tasks.sslt-cov]
+category = "RiseDev - Deterministic Simulation End-to-end Test"
+description = "Run e2e tests in deterministic simulation mode and report code coverage"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim-cov" }
+script = """
+#!/bin/bash
+set -e
+
+cargo llvm-cov run -p piestream_simulation --html "$@"
 """
 
 [tasks.check-hakari]
 category = "RiseDev - Check"
 description = "Run cargo hakari check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo hakari$(tput sgr0) checks and attempting to fix"
 
@@ -464,7 +566,7 @@ test $? -eq 0 || exit 1
 category = "RiseDev - Check"
 description = "Run cargo sort check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo sort$(tput sgr0) checks and attempting to fix"
 
@@ -477,7 +579,7 @@ test $? -eq 0 || { echo "cargo sort check failed. You may run $(tput setaf 4)car
 category = "RiseDev - Check"
 description = "Run cargo fmt check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo fmt$(tput sgr0) checks and attempting to fix"
 cargo fmt --all
@@ -488,12 +590,27 @@ test $? -eq 0 || exit 1
 category = "RiseDev - Check"
 description = "Run cargo clippy check"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo clippy$(tput sgr0) checks"
-cargo clippy --workspace --all-targets
+cargo clippy --all-targets --all-features
 echo "If cargo clippy check failed or generates warning, you may run $(tput setaf 4)cargo clippy --workspace --all-targets --fix$(tput sgr0) to fix it. Note that clippy fix requires manual review, as not all auto fixes are guaranteed to be reasonable."
 """
+
+[tasks.check-typos]
+category = "RiseDev - Check"
+description = "Run cargo typos-cli check"
+script = """
+#!/bin/bash
+if ! [ -x "$(command -v typos)" ]; then
+  echo "Error: 'typos-cli' is not installed, please run './risedev install-tools'." >&2
+  exit 1
+fi
+if ! typos ; then
+  echo "Hint: use 'typos -w' to fix."
+fi
+"""
+
 
 [tasks.check]
 category = "RiseDev - Check"
@@ -503,9 +620,10 @@ dependencies = [
   "check-dep-sort",
   "check-fmt",
   "check-clippy",
+  "check-typos",
 ]
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Good work! You may run $(tput setaf 4)./risedev test$(tput sgr0) or $(tput setaf 4)./risedev test-cov$(tput sgr0) to run unit tests."
 """
@@ -547,10 +665,10 @@ echo If you still feel this is not enough, you may copy $(tput setaf 4)risedev$(
 
 [tasks.ci-start]
 category = "RiseDev - CI"
-dependencies = ["clean-data", "pre-start-playground"]
-command = "target/${BUILD_MODE_DIR}/risedev-playground"
+dependencies = ["clean-data", "pre-start-dev"]
+command = "target/${BUILD_MODE_DIR}/risedev-dev"
 args = ["${@}"]
-description = "Clean data and start a full piestream dev cluster using risedev-playground"
+description = "Clean data and start a full piestream dev cluster using risedev-dev"
 
 [tasks.ci-kill]
 category = "RiseDev - CI"
@@ -560,19 +678,47 @@ description = "Kill cluster, dump logs and check logs"
 [tasks.slt]
 category = "RiseDev - SQLLogicTest"
 dependencies = ["warn-on-missing-tools"]
-script = """
+command = "sqllogictest"
+args = ["${@}"]
+description = "Run SQLLogicTest"
+
+[tasks.slt-streaming]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/streaming/**/*.slt"]
+description = "Run all streaming e2e tests"
+
+[tasks.slt-batch]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/batch/**/*.slt"]
+description = "Run all batch e2e tests"
+
+[tasks.slt-generated]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/generated/**/*.slt"]
+description = "Run all generated e2e tests"
+
+[tasks.slt-all]
+category = "RiseDev - SQLLogicTest"
+run_task = { name = ["slt-streaming", "slt-batch", "slt-generated"] }
+description = "Run all e2e tests"
+
+[tasks.docslt]
+category = "RiseDev - SQLLogicTest"
+description = "Extract SQL examples written in SQLLogicTest syntax from Rust doc comments"
+script = '''
 #!/bin/bash
 set -e
-
-sqllogictest "$@"
-"""
-description = "Run SQLLogicTest"
+cargo run --bin risedev-docslt -- "$@"
+'''
 
 [tasks.compose]
 category = "RiseDev - Compose"
 description = "Compose a docker-compose.yaml file"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -rf ${PREFIX_DOCKER}/*
 mkdir -p "${PREFIX_DOCKER}"
@@ -584,7 +730,7 @@ echo docker-compose file generated in $(tput setaf 4)${PREFIX_DOCKER}$(tput sgr0
 category = "RiseDev - Compose"
 description = "Compose a docker-compose.yaml deploy directory"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -rf "${PREFIX_DOCKER}"/*
 mkdir -p "${PREFIX_DOCKER}"
@@ -597,7 +743,7 @@ echo If you are ready, run $(tput setaf 4)./risedev apply-compose-deploy$(tput s
 category = "RiseDev - Compose"
 description = "Run deploy.sh"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 .piestream/rw-docker/deploy.sh "$@"
@@ -612,7 +758,7 @@ cat .piestream/rw-docker/_message.partial.sh
 category = "RiseDev - Compose"
 description = "Run deploy.sh"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 cp -a .piestream/rw-docker/* docker
